name: deploy-code

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        USERNAME: ubuntu
        HOST: ${{ secrets.HOST }}
        PASSWOD: ${{ secrets.PASSWORD }}
        script: whoami
